allprojects {
    group = 'dev.punctualboat.mantis'
    version = rootProject.mod_version
    repositories { mavenCentral() }
}

subprojects {
    apply plugin: 'java-library'
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
        withSourcesJar()
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }
    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.3')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
    tasks.withType(Test).configureEach { useJUnitPlatform() }
    tasks.withType(Jar).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
        manifest.attributes('Implementation-Vendor': 'PunctualBoat')
    }
}
