pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public' }
    }
}

rootProject.name = 'Mantis'
include 'mantis-core', 'mantis-runtime', 'mantis-recipes', 'mantis-minecraft'
